In [1]:
import numpy as np

import matplotlib as plt

from sklearn import datasets

from sklearn import metrics

from sklearn.linear_model import LogisticRegression

In [2]:
dataset = datasets.load_iris()

In [6]:
model = LogisticRegression(C=1e5)

model.fit(dataset.data, dataset.target)

expected = dataset.target

predicted = model.predict(dataset.data)

In [7]:
print(metrics.classification_report(expected, predicted))

print(metrics.confusion_matrix(expected, predicted))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        50
          1       0.98      0.96      0.97        50
          2       0.96      0.98      0.97        50

avg / total       0.98      0.98      0.98       150

[[50  0  0]
 [ 0 48  2]
 [ 0  1 49]]
